backend:
  name: git-gateway
  branch: main

  media_folder: static/images
  public_folder: ../../static/images/

  collection:
    - name: "destination"
      preview: false
      label: "Destination"
      folder: "content/destination"
      create: true
      slug: "{{slug}}"
      fields:
        - { label: "Location", name: "location", widget: "string" }
        - { label: "Travel Dates", name: "travel-dates", widget: "string" }
        - { label: "Featured Image", name: "featured-image", widget: image }
        - { label: "Body", name: "body", widget: "markdown" }